Add tfstate bootstrap in gcp deployment

diff --git a/infrastructure/quick-deploy/gcp/all-in-one/Makefile b/infrastructure/quick-deploy/gcp/all-in-one/Makefile
--- a/infrastructure/quick-deploy/gcp/all-in-one/Makefile
+++ b/infrastructure/quick-deploy/gcp/all-in-one/Makefile
@@ -25,6 +25,7 @@ export TF_VAR_region?=$(REGION)
 export TF_VAR_namespace?=$(NAMESPACE)
 export TF_VAR_prefix?=$(PREFIX)
 export TF_VAR_project?=$(PROJECT_ID)
+SHELL:=/bin/bash
 
 .PHONY: apply destroy
 
@@ -34,6 +35,40 @@ destroy: init delete
 
 env:
 	@set
+
+bootstrap-deploy:
+	@if [[ $${TFSTATE_BUCKET_NAME} =~ ^[a-z0-9]([-a-z0-9_]*[a-z0-9])?$$ && $${#TFSTATE_BUCKET_NAME} -ge 3 && $${#TFSTATE_BUCKET_NAME} -le 63 && ! $${TFSTATE_BUCKET_NAME} =~ -- && ! $${TFSTATE_BUCKET_NAME} =~ ^- && ! $${TFSTATE_BUCKET_NAME} =~ -$$ ]]; then \
+		echo "TFSTATE bucket Name : ${TFSTATE_BUCKET_NAME} is valid"; \
+	else \
+		echo -e "\e[91mError : Invalid TFSTATE bucket Name : '${TFSTATE_BUCKET_NAME}' ref: https://cloud.google.com/storage/docs/buckets#naming \e[0m"; \
+		exit 1; \
+	fi; \
+
+	@if gsutil ls -b gs://${TFSTATE_BUCKET_NAME} > /dev/null 2>&1; then \
+		echo "The bucket : ${TFSTATE_BUCKET_NAME} already exists."; \
+	else \
+		if gsutil mb -l ${TF_VAR_region} gs://${TFSTATE_BUCKET_NAME}; then \
+			echo "The bucket ${TFSTATE_BUCKET_NAME} in Region : '${TF_VAR_region}' has been successfuly created."; \
+		else \
+			echo -e "\e[91mError : TFSTATE bucket Name : '${TFSTATE_BUCKET_NAME}' has NOT been created. \e[0m"; \
+			gsutil ls -b gs://${TFSTATE_BUCKET_NAME}; \
+			exit 1; \
+		fi; \
+	fi
+
+bootstrap-destroy:
+	@if gsutil ls -b gs://${TFSTATE_BUCKET_NAME} > /dev/null 2>&1; then \
+		if gsutil rm -r gs://${TFSTATE_BUCKET_NAME}; then \
+		echo "The bucket : ${TFSTATE_BUCKET_NAME} has been deleted."; \
+		else \
+			echo -e "\e[91mError : The bucket : ${TFSTATE_BUCKET_NAME} has NOT been deleted. \e[0m"; \
+			gsutil ls -b gs://${TFSTATE_BUCKET_NAME}; \
+			exit 1; \
+		fi \
+	else \
+		echo "The bucket ${TFSTATE_BUCKET_NAME} is not in your bucket list."; \
+	fi 
+
 
 init:
 	mkdir -p $(TF_PLUGIN_CACHE_DIR)
